print("\t\t~*~*~*~*~*~*~ Simple Calculator ~*~*~*~*~*~*~\n")
num1 = float(input("enter the num1 = "))
num2 = float(input("enter the num2 = "))

print("Addition = ",num1+num2)
print("Substraction = ",num1-num2)
print("Multiplication = ",num1*num2)
print("Division = ",num1/num2)
print("Floor Division = ",num1//num2)
print("Exponents = ",num1**2)
print("Modulos = ",num1%num2)
